[package]
name = "progress_reporting"
version = "0.14.5"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "test_progress_reporting"
path = "src/main.rs"


[dependencies]
crossterm = "0.25.0"
utils = { path = "../utils" }
atty = "0.2"
