# /qompassai/qxet/.cargo/config.toml
# Qompass AI Qxet Cargo config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
