[package]
name = "cas_types"
version = "0.1.0"
edition = "2021"

[dependencies]
merklehash = { path = "../merklehash" }
thiserror = "2.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_repr = "0.1.19"
